<?php
session_start();

require '../vendor/autoload.php';
include '../auth/config/db.php';

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

if(!isset($_SESSION['user_id'])){
    die("Login required");
}

$user_id = $_SESSION['user_id'];

$stmt = $conn->prepare("
SELECT trusted_name, trusted_email
FROM users
WHERE id=?
");

$stmt->bind_param("i",$user_id);
$stmt->execute();

$user = $stmt->get_result()->fetch_assoc();

if(empty($user['trusted_email'])){
    die("No trusted contact found.");
}

$mail = new PHPMailer(true);

try{

    $mail->isSMTP();
    $mail->Host = 'smtp.gmail.com';
    $mail->SMTPAuth = true;

    // 👇 APNA GMAIL
    $mail->Username = $_ENV['SMTP_EMAIL'];
    

    // 👇 YAHAN APNA 16-CHAR APP PASSWORD PASTE KARNA
    
    $mail->Password = $_ENV['SMTP_PASSWORD'];

    $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
    $mail->Port = 587;

    $mail->setFrom('shivangt002@gmail.com','MindCare AI');

    $mail->addAddress(
        $user['trusted_email'],
        $user['trusted_name']
    );

    $mail->isHTML(true);

    $mail->Subject = "🚨 MindCare AI Emergency Alert";

    $mail->Body = "
    <h2>MindCare AI Emergency Alert</h2>

    <p>Hello <b>{$user['trusted_name']}</b>,</p>

    <p>
    This is an automated alert from MindCare AI.
    </p>

    <p>
    Your trusted person may be experiencing emotional distress.
    Please consider contacting them as soon as possible.
    </p>

    <hr>

    <p>
    This email was automatically generated by MindCare AI.
    </p>
    ";

    if($mail->send()){

    echo "success";

}else{

    echo "failed";

}

    echo "success";

}catch(Exception $e){

    error_log($mail->ErrorInfo);

echo "failed";   

}